version: '3.8'
services:
  gateway-service-tt:
    container_name: tt-gateway-service
    image: cr.yandex/crp0f2hu4uusc0520q40/gateway-service:develop
    ports:
      - 6049:6050
    env_file:
      - ../.env
    restart: always
