name: Dev CI/CD to Development server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DEVELOP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_SSH_KEY_DEVELOP }}
          passphrase: ${{ secrets.PASSPHRASE_DEVELOP }}
          script: |
            cd space21/staging/staging-deployment
            docker-compose --env-file ~/space21/staging/.env down
            git pull origin main
            docker-compose --env-file ~/space21/staging/.env up -d
            
#            docker-compose -f ~/space21/docker-compose-dev.yml --env-file ~/space21/.env_dev up -d auth-service
